apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "app.fullname" . }}-configmap

data:
  SPRING_DATASOURCE_URL: jdbc:mysql://{{ include "mysql.fullname" . }}:{{ .Values.database.port }}/{{ .Values.database.name }}

  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

  SPRING_JPA_HIBERNATE_DDL_AUTO: update

  SERVER_PORT: {{ .Values.service.targetPort | quote }}