apiVersion: external-secrets.io/v1
kind: SecretStore

metadata:
  name: aws-secrets

  namespace: {{ .Release.Namespace }}

spec:
  provider:
    aws:
      service: SecretsManager

      region: {{ .Values.externalSecret.region }}

      auth:
        secretRef:

          accessKeyIDSecretRef:
            name: aws-secret
            key: access-key-id

          secretAccessKeySecretRef:
            name: aws-secret
            key: secret-access-key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ include "app.fullname" . }}

  namespace: {{ .Release.Namespace }}

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets
    kind: SecretStore

  target:
    name: {{ include "app.fullname" . }}-secret

    creationPolicy: Owner

  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.secretName }}